#include "unity.h"
#include <stdio.h>
#if defined(_MSC_VER)
#include <stdlib.h>   // _set_error_mode, _OUT_TO_STDERR
#include <crtdbg.h>   // _CrtSetReportMode / _CrtSetReportFile (/RTC1 + assert routing)
#endif

void setUp(void) {}
// Flush after every test so that, if a later test crashes (e.g. a segfault on a
// CI runner), the log still shows every test that completed — the crashing test
// is the next one in RUN_TEST order. On Windows a pipe'd stdout is fully buffered,
// so without this a crash loses all output and the failing test is invisible.
void tearDown(void) { fflush(stdout); fflush(stderr); }

extern void test_string_raw_interpolation_and_arity(void);
extern void test_phase12_reserved_keywords(void);
extern void test_phase12_literal_suffixes(void);
extern void test_async_control_flow_and_raised_catch(void);
extern void test_concurrency_and_channel_semantics(void);
extern void test_cqrs_handler_with_dependency_injection(void);
extern void test_ffi_extern_struct_function_and_block_parsing(void);
extern void test_generics_type_parameters_and_where_constraints(void);
extern void test_extensions_methods_and_operator_overload_parsing(void);
extern void test_codegen_aot_c_transpilation_emits_runtime_and_statements(void);
extern void test_global_visibility_modifiers_and_service_restriction(void);
extern void test_parser_recovery_on_syntax_error(void);
extern void test_virtual_namespace_expansion_at_sign(void);
extern void test_reserved_namespace_protection(void);
extern void test_concurrency_methods_validation(void);
extern void test_symbol_table_scopes_and_mutability(void);
extern void test_required_properties_validation(void);
extern void test_type_compatibility_assignment(void);
extern void test_let_immutability_protection(void);
extern void test_bytecode_emission_and_constant_pooling(void);
extern void test_codegen_li_import_table_and_interop_emit(void);
extern void test_codegen_li_to_wasm_bridge(void);
extern void test_frontend_interop_extern_call_to_il(void);
extern void test_frontend_interop_dom_intrinsics(void);
extern void test_frontend_interop_routines_spawn(void);
extern void test_frontend_interop_duplex_lowering(void);
extern void test_frontend_interop_delayed_lowering(void);
extern void test_frontend_interop_broadcast_lowering(void);
extern void test_frontend_interop_shared_lowering(void);
extern void test_frontend_interop_timespan_normalization(void);
extern void test_codegen_li_object_family(void);
extern void test_codegen_li_vtable_family(void);
extern void test_codegen_li_call_func_sync(void);
extern void test_frontend_interop_class_concrete(void);
extern void test_frontend_interop_trait_grammar(void);
extern void test_frontend_interop_trait_collision(void);
extern void test_frontend_interop_trait_dynamic_dispatch(void);
extern void test_frontend_interop_generics_monomorphization(void);
extern void test_frontend_interop_event_fanout(void);
extern void test_frontend_interop_waiters_lowering(void);
extern void test_frontend_interop_controlflow_lowering(void);
extern void test_frontend_interop_resilience_lowering(void);
extern void test_frontend_interop_routine_loop(void);
extern void test_frontend_interop_routine_args(void);
extern void test_frontend_interop_time_lowering(void);
extern void test_frontend_interop_event_handler(void);
extern void test_frontend_interop_named_locals(void);
extern void test_frontend_interop_expressions(void);
extern void test_frontend_interop_nested_handle_args(void);
extern void test_frontend_interop_base_encoding(void);
extern void test_frontend_interop_hash_sha256(void);
extern void test_frontend_interop_hash_legacy(void);
extern void test_frontend_interop_uuid(void);
extern void test_di_lifetime_arena_assignment(void);
extern void test_escape_analysis_region_promotion(void);
extern void test_implicit_precision_coercion_for_arbitrary_types(void);
extern void test_composite_assignment_immutability_protection(void);
extern void test_elvis_operator_coalescence_semantics(void);
extern void test_safe_navigation_with_elvis_coalescence(void);
extern void test_teko_il_binary_header_integrity(void);
extern void test_vm_arena_linear_allocation_and_reset(void);
extern void test_vm_core_mathematical_execution_loop(void);
extern void test_vm_scheduler_context_switching_and_spawn(void);
extern void test_vm_channel_blocking_and_unblocking(void);
extern void test_vm_debugger_breakpoint_interception_and_dap(void);
extern void test_teko_project_manifest_parsing(void);
extern void test_vm_intrinsic_resolution_and_execution(void);
extern void test_virtual_sdk_injection_and_isolation(void);
extern void test_teko_lsp_protocol_handshake_and_routing(void);
extern void test_teko_bare_metal_target_detection_and_parsing(void);
extern void test_teko_cli_driver_assembly_mode_and_target_parsing(void);
extern void test_teko_cli_driver_object_mode_win_arm64(void);
extern void test_teko_cli_driver_default_host_fallback(void);
extern void test_teko_aot_darwin_x86_64_pure_emission(void);
extern void test_teko_aot_darwin_arm64_pure_emission(void);
extern void test_teko_aot_linux_x86_64_pure_emission(void);
extern void test_teko_aot_linux_x86_32_pure_emission(void);
extern void test_teko_aot_linux_riscv64_pure_emission(void);
extern void test_teko_aot_linux_riscv32_pure_emission(void);
extern void test_teko_aot_linux_ppc64_pure_emission(void);
extern void test_teko_aot_linux_mips_pure_emission(void);
extern void test_teko_aot_linux_arm64_pure_emission(void);
extern void test_teko_aot_linux_arm32_pure_emission(void);
extern void test_teko_aot_wasm_pure_emission_integrity(void);
extern void test_teko_aot_wasm_string_pool_data_segment(void);
extern void test_teko_aot_wasm_ffi_import_lowering(void);
extern void test_teko_aot_wasm_dom_import_lowering(void);
extern void test_teko_aot_wasm_event_callback_lowering(void);
extern void test_teko_aot_wasm_heap_allocator_runtime(void);
extern void test_teko_aot_wasm_facade_and_rich_event_lowering(void);
extern void test_teko_aot_wasm_arena_and_concurrency_hooks(void);
extern void test_teko_aot_wasm_multifunction_spawn_lowering(void);
extern void test_teko_aot_wasm_midfunction_suspension(void);
extern void test_teko_aot_wasm_threads_layer_b_emission(void);
extern void test_teko_aot_wasm_multispawn_contention(void);
extern void test_teko_aot_freebsd_x86_64_pure_emission(void);
extern void test_teko_aot_freebsd_arm64_pure_emission(void);
extern void test_teko_aot_windows_x86_32_pure_emission(void);
extern void test_teko_aot_windows_x86_64_pure_emission(void);
extern void test_teko_aot_windows_arm64_pure_emission(void);
extern void test_teko_aot_escape_analysis_register_allocation(void);
extern void test_teko_aot_dead_code_elimination_purgue(void);
extern void test_teko_aot_common_subexpression_elimination_filter(void);
extern void test_teko_aot_constant_folding_math_collapse(void);
extern void test_teko_linker_elf64_binary_header_generation(void);
extern void test_teko_linker_elf32_binary_header_and_class_validation(void);
extern void test_teko_linker_elf64_relative_jmp_patch_calculation(void);
extern void test_teko_linker_arch_x64_mov_encoding_integrity(void);
extern void test_teko_linker_arch_arm64_add_encoding_integrity(void);
extern void test_teko_linker_arch_x86_32_halt_encoding(void);
extern void test_teko_linker_arch_arm32_mov_encoding(void);
extern void test_teko_linker_arch_ppc64_add_encoding(void);
extern void test_tld_static_dependency_injection_and_symbol_resolution(void);
extern void test_teko_linker_e2e_extern_service_injection_and_elf_generation(void);
extern void test_teko_linker_wasm_leb128_compression_logic(void);
extern void test_teko_linker_macho_64_binary_signature_integrity(void);
extern void test_teko_linker_pe_coff_multi_architecture_signatures(void);
extern void test_codegen_emitters_arithmetic_per_target(void);

extern void test_teko_runtime_sys_allocation_and_page_recycling(void);
extern void test_teko_runtime_scheduler_cooperative_multithreading(void);
extern void test_teko_runtime_channels_blocking_and_signaling(void);
extern void test_teko_duplex_bidirectional_roundtrip(void);
extern void test_teko_duplex_capacity_full(void);
extern void test_teko_duplex_close_drains_then_signals(void);
extern void test_teko_duplex_drop_signals_peer(void);
extern void test_teko_duplex_badarg(void);
extern void test_teko_delayed_releases_in_time_order(void);
extern void test_teko_delayed_same_time_is_fifo(void);
extern void test_teko_delayed_capacity_and_close(void);
extern void test_teko_delayed_badarg(void);
extern void test_teko_broadcast_fanout_all_see_all(void);
extern void test_teko_broadcast_subscribe_is_future_only(void);
extern void test_teko_broadcast_lag_and_close(void);
extern void test_teko_broadcast_badarg(void);
extern void test_teko_atomic_cell_rmw(void);
extern void test_teko_shared_critical_section(void);
extern void test_teko_atomic_badarg(void);
extern void test_teko_object_new_zeroed(void);
extern void test_teko_object_set_get(void);
extern void test_teko_object_holds_handle(void);
extern void test_teko_object_bounds_and_null(void);
extern void test_teko_object_zero_fields(void);
extern void test_teko_vtable_set_get(void);
extern void test_teko_vtable_unset_is_minus_one(void);
extern void test_teko_vtable_override(void);
extern void test_teko_vtable_bounds(void);
extern void test_teko_retry_exponential_backoff(void);
extern void test_teko_retry_logarithmic_backoff(void);
extern void test_teko_retry_attempts_limit(void);
extern void test_teko_retry_timeout_branches_to_fallback(void);
extern void test_teko_circuit_breaker_transitions(void);
extern void test_teko_retry_badarg(void);
extern void test_teko_time_format_utc(void);
extern void test_teko_time_format_offset(void);
extern void test_teko_time_days_from_civil_roundtrip(void);
extern void test_teko_time_epoch_str_and_parse(void);
extern void test_teko_convert_i64_to_string(void);
extern void test_teko_convert_bool_to_string(void);
extern void test_teko_convert_str_concat(void);
extern void test_teko_convert_to_radix(void);
extern void test_teko_convert_pad(void);
extern void test_teko_convert_grouped(void);
extern void test_teko_convert_parse_i64_valid(void);
extern void test_teko_convert_parse_i64_invalid(void);
extern void test_teko_convert_parse_bool(void);
extern void test_teko_convert_f64_catalog(void);
extern void test_teko_convert_f64_roundtrip(void);
extern void test_teko_convert_f64_shortest(void);
extern void test_teko_convert_parse_f64_catalog(void);
extern void test_teko_convert_parse_f64_roundtrip(void);
extern void test_teko_convert_parse_f64_reject(void);
extern void test_teko_decimal_struct_layout(void);
extern void test_teko_decimal_from_components(void);
extern void test_teko_decimal_kat_vectors(void);
extern void test_teko_decimal_format_kats(void);
extern void test_teko_decimal_parse_kats(void);
extern void test_teko_decimal_roundtrips(void);
extern void test_teko_decimal_from_i32(void);
extern void test_teko_decimal_to_i32(void);
extern void test_teko_runtime_arena_thread_isolation_and_alignment(void);
extern void test_teko_crypto_md5_rfc1321_vectors(void);
extern void test_teko_crypto_md5_streaming_matches_oneshot(void);
extern void test_teko_crypto_sha1_fips180_vectors(void);
extern void test_teko_crypto_sha1_streaming_matches_oneshot(void);
extern void test_teko_crypto_sha256_known_answer_vectors(void);
extern void test_teko_crypto_sha256_streaming_matches_oneshot(void);
extern void test_teko_crypto_sha512_known_answer_vectors(void);
extern void test_teko_crypto_sha384_known_answer_vectors(void);
extern void test_teko_crypto_sha512_streaming_matches_oneshot(void);
extern void test_teko_crypto_hmac_rfc4231_vectors(void);
extern void test_teko_crypto_sha3_known_answer_vectors(void);
extern void test_teko_crypto_shake_known_answer_vectors(void);
extern void test_teko_crypto_blake3_known_answer_vectors(void);
extern void test_teko_crypto_blake3_streaming_matches_oneshot(void);
extern void test_teko_crypto_csprng_fills_and_differs(void);
extern void test_teko_crypto_csprng_distribution_sanity(void);
extern void test_teko_crypto_hkdf_rfc5869_vectors(void);
extern void test_teko_crypto_hkdf_sha512_structural(void);
extern void test_teko_crypto_pbkdf2_sha256_rfc7914_vectors(void);
extern void test_teko_crypto_pbkdf2_sha512_structural(void);
extern void test_teko_crypto_chacha20_rfc8439_encrypt(void);
extern void test_teko_crypto_chacha20_rfc8439_block(void);
extern void test_teko_crypto_poly1305_rfc8439_vector(void);
extern void test_teko_crypto_poly1305_streaming_matches_oneshot(void);
extern void test_teko_crypto_chachapoly_rfc8439_aead(void);
extern void test_teko_crypto_chachapoly_rejects_tampering(void);
extern void test_teko_crypto_aes_fips197_blocks(void);
extern void test_teko_crypto_aes128_nist_vector(void);
extern void test_teko_crypto_aes_ctr_nist_vector(void);
extern void test_teko_crypto_aes_cbc_nist_vector(void);
extern void test_teko_crypto_aes_gcm_case3(void);
extern void test_teko_crypto_aes_gcm_case4(void);
extern void test_teko_crypto_scrypt_rfc7914_vectors(void);
extern void test_teko_crypto_blake2b_known_answer_vectors(void);
extern void test_teko_crypto_blake2b_streaming_matches_oneshot(void);
extern void test_teko_crypto_argon2_rfc9106_vectors(void);
extern void test_teko_crypto_argon2i_rfc9106_vector(void);
extern void test_teko_crypto_argon2id_rfc9106_vector(void);
extern void test_teko_crypto_x25519_rfc7748_vectors(void);
extern void test_teko_crypto_x25519_dh_agreement(void);
extern void test_teko_crypto_ed25519_rfc8032_test1(void);
extern void test_teko_crypto_ed25519_sign_verify_roundtrip(void);
extern void test_teko_uuid_known_answer_vectors(void);
extern void test_teko_uuid_parse_format(void);
extern void test_teko_uuid_v4_structure(void);
extern void test_teko_uuid_v7_structure(void);
extern void test_teko_uuid_v8_structure(void);
extern void test_teko_bn_modexp_rsa3233(void);
extern void test_teko_bn_modexp_fermat_p256(void);
extern void test_teko_bn_modexp_identity(void);
extern void test_teko_bn_fieldops_smallmod(void);
extern void test_teko_bn_fieldops_montmul_vs_modexp(void);
extern void test_teko_bn_fieldops_addsub_and_select(void);
extern void test_teko_p256_ecdh_cavp_count0(void);
extern void test_teko_p256_ecdh_cavp_count1(void);
extern void test_teko_p256_ecdh_rejects_offcurve(void);
extern void test_teko_p256_ecdsa_rfc6979_sample(void);
extern void test_teko_p256_ecdsa_rfc6979_test(void);
extern void test_teko_p384_ecdh_cavp_count0(void);
extern void test_teko_p384_ecdsa_rfc6979_sample(void);
extern void test_teko_p384_ecdsa_rfc6979_test(void);
extern void test_teko_p384_ecdh_rejects_offcurve(void);
extern void test_teko_rsa_pkcs1v15_sha256_kat(void);
extern void test_teko_rsa_pkcs1v15_encrypt_roundtrip(void);
extern void test_teko_rsa_oaep_sha256_kat(void);
extern void test_teko_rsa_pss_sha256_kat(void);

/* Phase 19 (ROUTER-CORE Wave 0) */
extern void test_teko_router_build(void);
extern void test_teko_router_exact_match(void);
extern void test_teko_router_param_match(void);
extern void test_teko_router_literal_beats_param(void);
extern void test_teko_router_method_mismatch_405(void);
extern void test_teko_router_no_match_404(void);
extern void test_teko_router_middleware_order(void);
extern void test_teko_router_synthetic_e2e(void);
extern void test_teko_router_badarg_hardening(void);
// Phase 19 (T1a) — client socket runtime KATs
extern void test_teko_socket_null_args(void);
extern void test_teko_socket_recv_bounds_constant(void);
extern void test_teko_socket_handle_table_constant(void);
extern void test_teko_socket_state_machine(void);
extern void test_teko_socket_loopback_roundtrip(void);
extern void test_teko_socket_recv_bounds_gate(void);
extern void test_teko_socket_send_on_closed(void);
// Phase 19 (T1b, Wave 0) — server socket KATs (NATIVE-ONLY; compiled only when !defined(__wasm__)).
#if !defined(__wasm__)
extern void test_teko_server_alloc_free(void);
extern void test_teko_server_badarg(void);
extern void test_teko_server_accept_again_when_idle(void);
extern void test_teko_server_cap_enforcement(void);
extern void test_teko_server_loopback_roundtrip(void);
#endif

int main(void) {
    // Unbuffered output: stream every line live so a crash on a CI runner shows
    // exactly how far the suite got (Windows pipes are otherwise fully buffered).
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

#if defined(_MSC_VER)
    // CI diagnostics: route the MSVC CRT error/assert and runtime-check (/RTC1)
    // reports to stderr instead of a GUI message box, so a /RTC "used without
    // being initialized" failure prints its file:line and aborts non-interactively
    // on a headless runner (otherwise it would hang waiting on a dialog).
    _set_error_mode(_OUT_TO_STDERR);
    _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_ERROR, _CRTDBG_FILE_STDERR);
    _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_ASSERT, _CRTDBG_FILE_STDERR);
#endif

    UNITY_BEGIN();

    RUN_TEST(test_string_raw_interpolation_and_arity);
    RUN_TEST(test_phase12_reserved_keywords);
    RUN_TEST(test_phase12_literal_suffixes);
    RUN_TEST(test_async_control_flow_and_raised_catch);
    RUN_TEST(test_cqrs_handler_with_dependency_injection);
    RUN_TEST(test_ffi_extern_struct_function_and_block_parsing);
    RUN_TEST(test_generics_type_parameters_and_where_constraints);
    RUN_TEST(test_extensions_methods_and_operator_overload_parsing);
    RUN_TEST(test_codegen_aot_c_transpilation_emits_runtime_and_statements);
    RUN_TEST(test_parser_recovery_on_syntax_error);
    RUN_TEST(test_global_visibility_modifiers_and_service_restriction);
    RUN_TEST(test_virtual_namespace_expansion_at_sign);
    RUN_TEST(test_reserved_namespace_protection);
    RUN_TEST(test_concurrency_and_channel_semantics);
    RUN_TEST(test_concurrency_methods_validation);
    RUN_TEST(test_symbol_table_scopes_and_mutability);
    RUN_TEST(test_required_properties_validation);
    RUN_TEST(test_type_compatibility_assignment);
    RUN_TEST(test_let_immutability_protection);
    RUN_TEST(test_bytecode_emission_and_constant_pooling);
    RUN_TEST(test_codegen_li_import_table_and_interop_emit);
    RUN_TEST(test_codegen_li_to_wasm_bridge);
    RUN_TEST(test_frontend_interop_extern_call_to_il);
    RUN_TEST(test_frontend_interop_dom_intrinsics);
    RUN_TEST(test_frontend_interop_routines_spawn);
    RUN_TEST(test_frontend_interop_duplex_lowering);
    RUN_TEST(test_frontend_interop_delayed_lowering);
    RUN_TEST(test_frontend_interop_broadcast_lowering);
    RUN_TEST(test_frontend_interop_shared_lowering);
    RUN_TEST(test_frontend_interop_timespan_normalization);
    RUN_TEST(test_codegen_li_object_family);
    RUN_TEST(test_codegen_li_vtable_family);
    RUN_TEST(test_codegen_li_call_func_sync);
    RUN_TEST(test_frontend_interop_class_concrete);
    RUN_TEST(test_frontend_interop_trait_grammar);
    RUN_TEST(test_frontend_interop_trait_collision);
    RUN_TEST(test_frontend_interop_trait_dynamic_dispatch);
    RUN_TEST(test_frontend_interop_generics_monomorphization);
    RUN_TEST(test_frontend_interop_event_fanout);
    RUN_TEST(test_frontend_interop_waiters_lowering);
    RUN_TEST(test_frontend_interop_controlflow_lowering);
    RUN_TEST(test_frontend_interop_resilience_lowering);
    RUN_TEST(test_frontend_interop_routine_loop);
    RUN_TEST(test_frontend_interop_routine_args);
    RUN_TEST(test_frontend_interop_time_lowering);
    RUN_TEST(test_frontend_interop_event_handler);
    RUN_TEST(test_frontend_interop_named_locals);
    RUN_TEST(test_frontend_interop_expressions);
    RUN_TEST(test_frontend_interop_nested_handle_args);
    RUN_TEST(test_frontend_interop_base_encoding);
    RUN_TEST(test_frontend_interop_hash_sha256);
    RUN_TEST(test_frontend_interop_hash_legacy);
    RUN_TEST(test_frontend_interop_uuid);
    RUN_TEST(test_di_lifetime_arena_assignment);
    RUN_TEST(test_escape_analysis_region_promotion);
    RUN_TEST(test_implicit_precision_coercion_for_arbitrary_types);
    RUN_TEST(test_composite_assignment_immutability_protection);
    RUN_TEST(test_elvis_operator_coalescence_semantics);
    RUN_TEST(test_safe_navigation_with_elvis_coalescence);
    RUN_TEST(test_teko_il_binary_header_integrity);
    RUN_TEST(test_vm_arena_linear_allocation_and_reset);
    RUN_TEST(test_vm_core_mathematical_execution_loop);
    RUN_TEST(test_vm_scheduler_context_switching_and_spawn);
    RUN_TEST(test_vm_channel_blocking_and_unblocking);
    RUN_TEST(test_vm_debugger_breakpoint_interception_and_dap);
    RUN_TEST(test_teko_project_manifest_parsing);
    RUN_TEST(test_vm_intrinsic_resolution_and_execution);
    RUN_TEST(test_virtual_sdk_injection_and_isolation);
    RUN_TEST(test_teko_lsp_protocol_handshake_and_routing);
    RUN_TEST(test_teko_bare_metal_target_detection_and_parsing);
    RUN_TEST(test_teko_cli_driver_assembly_mode_and_target_parsing);
    RUN_TEST(test_teko_cli_driver_object_mode_win_arm64);
    RUN_TEST(test_teko_cli_driver_default_host_fallback);
    RUN_TEST(test_teko_aot_darwin_x86_64_pure_emission);
    RUN_TEST(test_teko_aot_darwin_arm64_pure_emission);
    RUN_TEST(test_teko_aot_linux_x86_64_pure_emission);
    RUN_TEST(test_teko_aot_linux_x86_32_pure_emission);
    RUN_TEST(test_teko_aot_linux_riscv64_pure_emission);
    RUN_TEST(test_teko_aot_linux_riscv32_pure_emission);
    RUN_TEST(test_teko_aot_linux_ppc64_pure_emission);
    RUN_TEST(test_teko_aot_linux_mips_pure_emission);
    RUN_TEST(test_teko_aot_linux_arm64_pure_emission);
    RUN_TEST(test_teko_aot_linux_arm32_pure_emission);
    RUN_TEST(test_teko_aot_wasm_pure_emission_integrity);
    RUN_TEST(test_teko_aot_wasm_string_pool_data_segment);
    RUN_TEST(test_teko_aot_wasm_ffi_import_lowering);
    RUN_TEST(test_teko_aot_wasm_dom_import_lowering);
    RUN_TEST(test_teko_aot_wasm_event_callback_lowering);
    RUN_TEST(test_teko_aot_wasm_heap_allocator_runtime);
    RUN_TEST(test_teko_aot_wasm_facade_and_rich_event_lowering);
    RUN_TEST(test_teko_aot_wasm_arena_and_concurrency_hooks);
    RUN_TEST(test_teko_aot_wasm_multifunction_spawn_lowering);
    RUN_TEST(test_teko_aot_wasm_midfunction_suspension);
    RUN_TEST(test_teko_aot_wasm_threads_layer_b_emission);
    RUN_TEST(test_teko_aot_wasm_multispawn_contention);
    RUN_TEST(test_teko_aot_freebsd_x86_64_pure_emission);
    RUN_TEST(test_teko_aot_freebsd_arm64_pure_emission);
    RUN_TEST(test_teko_aot_windows_x86_32_pure_emission);
    RUN_TEST(test_teko_aot_windows_x86_64_pure_emission);
    RUN_TEST(test_teko_aot_windows_arm64_pure_emission);
    RUN_TEST(test_teko_aot_escape_analysis_register_allocation);
    RUN_TEST(test_teko_aot_dead_code_elimination_purgue);
    RUN_TEST(test_teko_aot_common_subexpression_elimination_filter);
    RUN_TEST(test_teko_aot_constant_folding_math_collapse);
    RUN_TEST(test_teko_linker_elf64_binary_header_generation);
    RUN_TEST(test_teko_linker_elf64_relative_jmp_patch_calculation);
    RUN_TEST(test_teko_linker_arch_x64_mov_encoding_integrity);
    RUN_TEST(test_teko_linker_arch_arm64_add_encoding_integrity);
    RUN_TEST(test_teko_linker_arch_x86_32_halt_encoding);
    RUN_TEST(test_teko_linker_arch_arm32_mov_encoding);
    RUN_TEST(test_teko_linker_arch_ppc64_add_encoding);
    RUN_TEST(test_tld_static_dependency_injection_and_symbol_resolution);
    RUN_TEST(test_teko_linker_e2e_extern_service_injection_and_elf_generation);
    RUN_TEST(test_teko_linker_elf32_binary_header_and_class_validation);
    RUN_TEST(test_teko_linker_wasm_leb128_compression_logic);
    RUN_TEST(test_teko_linker_macho_64_binary_signature_integrity);
    RUN_TEST(test_teko_linker_pe_coff_multi_architecture_signatures);
    RUN_TEST(test_codegen_emitters_arithmetic_per_target);

    RUN_TEST(test_teko_runtime_sys_allocation_and_page_recycling);
    RUN_TEST(test_teko_runtime_scheduler_cooperative_multithreading);
    RUN_TEST(test_teko_runtime_channels_blocking_and_signaling);
    RUN_TEST(test_teko_duplex_bidirectional_roundtrip);
    RUN_TEST(test_teko_duplex_capacity_full);
    RUN_TEST(test_teko_duplex_close_drains_then_signals);
    RUN_TEST(test_teko_duplex_drop_signals_peer);
    RUN_TEST(test_teko_duplex_badarg);
    RUN_TEST(test_teko_delayed_releases_in_time_order);
    RUN_TEST(test_teko_delayed_same_time_is_fifo);
    RUN_TEST(test_teko_delayed_capacity_and_close);
    RUN_TEST(test_teko_delayed_badarg);
    RUN_TEST(test_teko_broadcast_fanout_all_see_all);
    RUN_TEST(test_teko_broadcast_subscribe_is_future_only);
    RUN_TEST(test_teko_broadcast_lag_and_close);
    RUN_TEST(test_teko_broadcast_badarg);
    RUN_TEST(test_teko_atomic_cell_rmw);
    RUN_TEST(test_teko_shared_critical_section);
    RUN_TEST(test_teko_atomic_badarg);
    RUN_TEST(test_teko_object_new_zeroed);
    RUN_TEST(test_teko_object_set_get);
    RUN_TEST(test_teko_object_holds_handle);
    RUN_TEST(test_teko_object_bounds_and_null);
    RUN_TEST(test_teko_object_zero_fields);
    RUN_TEST(test_teko_vtable_set_get);
    RUN_TEST(test_teko_vtable_unset_is_minus_one);
    RUN_TEST(test_teko_vtable_override);
    RUN_TEST(test_teko_vtable_bounds);
    RUN_TEST(test_teko_retry_exponential_backoff);
    RUN_TEST(test_teko_retry_logarithmic_backoff);
    RUN_TEST(test_teko_retry_attempts_limit);
    RUN_TEST(test_teko_retry_timeout_branches_to_fallback);
    RUN_TEST(test_teko_circuit_breaker_transitions);
    RUN_TEST(test_teko_retry_badarg);
    RUN_TEST(test_teko_time_format_utc);
    RUN_TEST(test_teko_time_format_offset);
    RUN_TEST(test_teko_time_days_from_civil_roundtrip);
    RUN_TEST(test_teko_time_epoch_str_and_parse);
    RUN_TEST(test_teko_convert_i64_to_string);
    RUN_TEST(test_teko_convert_bool_to_string);
    RUN_TEST(test_teko_convert_str_concat);
    RUN_TEST(test_teko_convert_to_radix);
    RUN_TEST(test_teko_convert_pad);
    RUN_TEST(test_teko_convert_grouped);
    RUN_TEST(test_teko_convert_parse_i64_valid);
    RUN_TEST(test_teko_convert_parse_i64_invalid);
    RUN_TEST(test_teko_convert_parse_bool);
    RUN_TEST(test_teko_convert_f64_catalog);
    RUN_TEST(test_teko_convert_f64_roundtrip);
    RUN_TEST(test_teko_convert_f64_shortest);
    RUN_TEST(test_teko_convert_parse_f64_catalog);
    RUN_TEST(test_teko_convert_parse_f64_roundtrip);
    RUN_TEST(test_teko_convert_parse_f64_reject);
    RUN_TEST(test_teko_decimal_struct_layout);
    RUN_TEST(test_teko_decimal_from_components);
    RUN_TEST(test_teko_decimal_kat_vectors);
    RUN_TEST(test_teko_decimal_format_kats);
    RUN_TEST(test_teko_decimal_parse_kats);
    RUN_TEST(test_teko_decimal_roundtrips);
    RUN_TEST(test_teko_decimal_from_i32);
    RUN_TEST(test_teko_decimal_to_i32);
    RUN_TEST(test_teko_runtime_arena_thread_isolation_and_alignment);

    RUN_TEST(test_teko_crypto_md5_rfc1321_vectors);
    RUN_TEST(test_teko_crypto_md5_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_sha1_fips180_vectors);
    RUN_TEST(test_teko_crypto_sha1_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_sha256_known_answer_vectors);
    RUN_TEST(test_teko_crypto_sha256_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_sha512_known_answer_vectors);
    RUN_TEST(test_teko_crypto_sha384_known_answer_vectors);
    RUN_TEST(test_teko_crypto_sha512_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_hmac_rfc4231_vectors);
    RUN_TEST(test_teko_crypto_sha3_known_answer_vectors);
    RUN_TEST(test_teko_crypto_shake_known_answer_vectors);
    RUN_TEST(test_teko_crypto_blake3_known_answer_vectors);
    RUN_TEST(test_teko_crypto_blake3_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_csprng_fills_and_differs);
    RUN_TEST(test_teko_crypto_csprng_distribution_sanity);
    RUN_TEST(test_teko_crypto_hkdf_rfc5869_vectors);
    RUN_TEST(test_teko_crypto_hkdf_sha512_structural);
    RUN_TEST(test_teko_crypto_pbkdf2_sha256_rfc7914_vectors);
    RUN_TEST(test_teko_crypto_pbkdf2_sha512_structural);
    RUN_TEST(test_teko_crypto_chacha20_rfc8439_encrypt);
    RUN_TEST(test_teko_crypto_chacha20_rfc8439_block);
    RUN_TEST(test_teko_crypto_poly1305_rfc8439_vector);
    RUN_TEST(test_teko_crypto_poly1305_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_chachapoly_rfc8439_aead);
    RUN_TEST(test_teko_crypto_chachapoly_rejects_tampering);
    RUN_TEST(test_teko_crypto_aes_fips197_blocks);
    RUN_TEST(test_teko_crypto_aes128_nist_vector);
    RUN_TEST(test_teko_crypto_aes_ctr_nist_vector);
    RUN_TEST(test_teko_crypto_aes_cbc_nist_vector);
    RUN_TEST(test_teko_crypto_aes_gcm_case3);
    RUN_TEST(test_teko_crypto_aes_gcm_case4);
    RUN_TEST(test_teko_crypto_scrypt_rfc7914_vectors);
    RUN_TEST(test_teko_crypto_blake2b_known_answer_vectors);
    RUN_TEST(test_teko_crypto_blake2b_streaming_matches_oneshot);
    RUN_TEST(test_teko_crypto_argon2_rfc9106_vectors);
    RUN_TEST(test_teko_crypto_argon2i_rfc9106_vector);
    RUN_TEST(test_teko_crypto_argon2id_rfc9106_vector);
    RUN_TEST(test_teko_crypto_x25519_rfc7748_vectors);
    RUN_TEST(test_teko_crypto_x25519_dh_agreement);
    RUN_TEST(test_teko_crypto_ed25519_rfc8032_test1);
    RUN_TEST(test_teko_crypto_ed25519_sign_verify_roundtrip);
    RUN_TEST(test_teko_uuid_known_answer_vectors);
    RUN_TEST(test_teko_uuid_parse_format);
    RUN_TEST(test_teko_uuid_v4_structure);
    RUN_TEST(test_teko_uuid_v7_structure);
    RUN_TEST(test_teko_uuid_v8_structure);
    RUN_TEST(test_teko_bn_modexp_rsa3233);
    RUN_TEST(test_teko_bn_modexp_fermat_p256);
    RUN_TEST(test_teko_bn_modexp_identity);
    RUN_TEST(test_teko_bn_fieldops_smallmod);
    RUN_TEST(test_teko_bn_fieldops_montmul_vs_modexp);
    RUN_TEST(test_teko_bn_fieldops_addsub_and_select);
    RUN_TEST(test_teko_p256_ecdh_cavp_count0);
    RUN_TEST(test_teko_p256_ecdh_cavp_count1);
    RUN_TEST(test_teko_p256_ecdh_rejects_offcurve);
    RUN_TEST(test_teko_p256_ecdsa_rfc6979_sample);
    RUN_TEST(test_teko_p256_ecdsa_rfc6979_test);
    RUN_TEST(test_teko_p384_ecdh_cavp_count0);
    RUN_TEST(test_teko_p384_ecdsa_rfc6979_sample);
    RUN_TEST(test_teko_p384_ecdsa_rfc6979_test);
    RUN_TEST(test_teko_p384_ecdh_rejects_offcurve);
    RUN_TEST(test_teko_rsa_pkcs1v15_sha256_kat);
    RUN_TEST(test_teko_rsa_pkcs1v15_encrypt_roundtrip);
    RUN_TEST(test_teko_rsa_oaep_sha256_kat);
    RUN_TEST(test_teko_rsa_pss_sha256_kat);

    /* Phase 19 (ROUTER-CORE Wave 0) -- target-agnostic radix-tree router KATs */
    RUN_TEST(test_teko_router_build);
    RUN_TEST(test_teko_router_exact_match);
    RUN_TEST(test_teko_router_param_match);
    RUN_TEST(test_teko_router_literal_beats_param);
    RUN_TEST(test_teko_router_method_mismatch_405);
    RUN_TEST(test_teko_router_no_match_404);
    RUN_TEST(test_teko_router_middleware_order);
    RUN_TEST(test_teko_router_synthetic_e2e);
    RUN_TEST(test_teko_router_badarg_hardening);
    // Phase 19 (T1a) — client socket runtime KATs
    RUN_TEST(test_teko_socket_null_args);
    RUN_TEST(test_teko_socket_recv_bounds_constant);
    RUN_TEST(test_teko_socket_handle_table_constant);
    RUN_TEST(test_teko_socket_state_machine);
    RUN_TEST(test_teko_socket_loopback_roundtrip);
    RUN_TEST(test_teko_socket_recv_bounds_gate);
    RUN_TEST(test_teko_socket_send_on_closed);
    // Phase 19 (T1b, Wave 0) — server socket KATs (NATIVE-ONLY).
#if !defined(__wasm__)
    RUN_TEST(test_teko_server_alloc_free);
    RUN_TEST(test_teko_server_badarg);
    RUN_TEST(test_teko_server_accept_again_when_idle);
    RUN_TEST(test_teko_server_cap_enforcement);
    RUN_TEST(test_teko_server_loopback_roundtrip);
#endif

    return UNITY_END();
}