#include "unity.h"
#include "teko_il.h"
#include "codegen_li.h"
#include <stdio.h>
#include <stdlib.h>

// Validates the physical integrity of the .tkb file header generated by the compiler
void test_teko_il_binary_header_integrity(void) {
    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);

    // Feeds the context with dummy test data
    codegen_li_add_string_constant(buffer, "TekoMain");

    // Simulates writing the binary
    const char* test_file = "output_spec_test.tkb";
    teko_il_serialize_binary(buffer, test_file);

    // Opens the generated file to inspect the physical header bytes
    FILE* file = fopen(test_file, "rb");
    TEST_ASSERT_NOT_NULL(file);

    TekoFileHeader read_header;
    size_t read_bytes = fread(&read_header, sizeof(TekoFileHeader), 1, file);
    fclose(file);

    // Unity assertions validating the file memory layout
    TEST_ASSERT_EQUAL_INT(1, read_bytes);
    TEST_ASSERT_EQUAL_UINT32(TEKO_MAGIC, read_header.magic);
    TEST_ASSERT_EQUAL_UINT16(TEKO_VERSION_MAJOR, read_header.version_major);
    TEST_ASSERT_EQUAL_UINT32(1, read_header.constant_pool_count);

    // Environment cleanup
    remove(test_file);
    codegen_li_free_context(buffer);
}