#include "unity.h"
#include "codegen_li.h"
#include "codegen_li_wasm.h"
#include "frontend_interop.h"
#include "teko_target.h"
#include "parser_statements.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Validates whether the emitter generates the correct opcodes and manages the String Pool without duplicating items
void test_bytecode_emission_and_constant_pooling(void) {
    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);

    // Adds repeated string constants in an induced manner
    int idx1 = codegen_li_add_string_constant(buffer, "abc");
    int idx2 = codegen_li_add_string_constant(buffer, "abc");
    int idx3 = codegen_li_add_string_constant(buffer, "xyz");

    // Validates that the constant pool rejected the duplicate and optimized the indices
    TEST_ASSERT_EQUAL_INT(idx1, idx2);
    TEST_ASSERT_EQUAL_INT(0, idx1);
    TEST_ASSERT_EQUAL_INT(1, idx3);

    // Instantiates a dummy constant variable declaration statement (const constant = "abc";)
    StatementASTNode stmt;
    stmt.type = NODE_VAR_DECL;
    stmt.data.var_decl.is_mutable = false;
    stmt.data.var_decl.var_name = strdup("constant");
    stmt.data.var_decl.initializer_raw = strdup("\"abc\"");
    stmt.data.var_decl.var_type = NULL;

    // Emits the bytecode for the statement
    codegen_li_emit_statement(buffer, &stmt);

    // The generated byte stream should contain: OP_SCONST (0x02) + pool index (0) + OP_STORE (0x04)
    TEST_ASSERT_TRUE(buffer->size > 0);
    TEST_ASSERT_EQUAL_UINT8(OP_SCONST, buffer->code[0]);

    // Executes a simulated write to disk to verify the magic header
    codegen_li_write_to_file(buffer, "test_output.tkb");

    // Cleanup
    free(stmt.data.var_decl.var_name);
    free(stmt.data.var_decl.initializer_raw);
    codegen_li_free_context(buffer);
}

// Phase 11 (Browser FFI frontend FE-B): bridge a frontend IL BytecodeBuffer to the
// WASM backend (codegen_li_emit_wasm) and assert the emitted .wat carries the import,
// the call site, and the string pool data segment — IL -> WASM without a parser.
void test_codegen_li_to_wasm_bridge(void) {
    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);

    int imp = codegen_li_add_import(buffer, "env", "log", 1, 0);
    int s = codegen_li_add_string_constant(buffer, "hi");
    codegen_li_emit_sconst(buffer, s);
    codegen_li_emit_call_import(buffer, imp);
    codegen_li_emit_halt(buffer);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);

    const char* wat = "output_li_wasm_bridge.wat";
    int rc = codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0);
    TEST_ASSERT_EQUAL_INT(0, rc);

    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(16384);
    TEST_ASSERT_NOT_NULL(out);
    memset(out, 0, 16384);
    size_t n = fread(out, 1, 16383, f);
    out[n] = '\0';
    fclose(f);

    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"log\" (func $import_0 (param i32)))"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $import_0"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(data (i32.const 1024) \"hi\\00\")"));

    free(out);
    remove(wat);
    codegen_li_free_context(buffer);
}

// Phase 11 (Browser FFI frontend FE-C): compile REAL Teko source (extern + call)
// to IL via the interop frontend, and through the bridge to WASM — proving
// source -> IL -> WASM, not an emit-demo.
void test_frontend_interop_extern_call_to_il(void) {
    const char* src =
        "extern fn log(msg: str) from \"env\" as \"log\";\n"
        "log(\"hello from source\");\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // The extern was consumed into the import table (ns=from, name=as).
    TEST_ASSERT_EQUAL_INT(1, buffer->import_count);
    TEST_ASSERT_EQUAL_STRING("env", buffer->imports[0].ns);
    TEST_ASSERT_EQUAL_STRING("log", buffer->imports[0].name);
    TEST_ASSERT_EQUAL_INT(1, buffer->imports[0].n_params);

    // The call pooled its string and lowered to SCONST -> CALL_IMPORT -> HALT.
    TEST_ASSERT_EQUAL_INT(0, codegen_li_add_string_constant(buffer, "hello from source")); // already pooled at 0
    const unsigned char expected[] = {
        0x02, 0x00, 0x00, 0x00, 0x00, // OP_SCONST 0
        0x09, 0x00, 0x00, 0x00, 0x00, // OP_CALL_IMPORT 0
        0x00                          // OP_HALT
    };
    TEST_ASSERT_EQUAL_INT((int)sizeof(expected), buffer->size);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, buffer->code, sizeof(expected));

    // Through the bridge: a real .wat with the import, call, and data segment.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_src.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));

    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(16384);
    memset(out, 0, 16384);
    size_t n = fread(out, 1, 16383, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"log\" (func $import_0 (param i32)))"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $import_0"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(data (i32.const 1024) \"hello from source\\00\")"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 11 (Browser FFI frontend FE-E): @dom intrinsics from real source. A nested
// `@dom.getElementById("out")` feeds `@dom.setText(…, "…")`; strings expand to
// (ptr,len). Asserts the auto-registered dom.* imports + the lowered IL shape.
void test_frontend_interop_dom_intrinsics(void) {
    const char* src =
        "@dom.setText(@dom.getElementById(\"out\"), \"hi there\");\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // Two dom imports auto-registered: getElementById (2 params, result) then setText
    // (3 params, no result).
    TEST_ASSERT_EQUAL_INT(2, buffer->import_count);
    TEST_ASSERT_EQUAL_STRING("dom", buffer->imports[0].ns);
    TEST_ASSERT_EQUAL_STRING("getElementById", buffer->imports[0].name);
    TEST_ASSERT_EQUAL_INT(2, buffer->imports[0].n_params);
    TEST_ASSERT_EQUAL_INT(1, buffer->imports[0].has_result);
    TEST_ASSERT_EQUAL_STRING("setText", buffer->imports[1].name);
    TEST_ASSERT_EQUAL_INT(3, buffer->imports[1].n_params);
    TEST_ASSERT_EQUAL_INT(0, buffer->imports[1].has_result);

    // IL (P12-F generalized nesting): the nested getElementById is lowered first and
    // its handle spilled to a temp local ($v0); setText then loads it back during arg
    // staging. So:
    //   getElementById("out") -> SCONST"out", SETARG0, ICONST3, CALL_IMPORT0
    //   STORE_LOCAL 0                              (park handle)
    //   setText: LOAD_LOCAL0, SETARG0, SCONST"hi there", SETARG1, ICONST8, CALL_IMPORT1
    //   HALT
    const unsigned char expected[] = {
        0x02, 0x00, 0x00, 0x00, 0x00, // SCONST 0 ("out")
        0x0A, 0x00, 0x00, 0x00, 0x00, // SETARG 0
        0x01, 0x03, 0x00, 0x00, 0x00, // ICONST 3
        0x09, 0x00, 0x00, 0x00, 0x00, // CALL_IMPORT 0 (getElementById) -> $w0 = handle
        0x0C, 0x00, 0x00, 0x00, 0x00, // STORE_LOCAL 0 (park handle in temp $v0)
        0x0B, 0x00, 0x00, 0x00, 0x00, // LOAD_LOCAL 0 (handle)
        0x0A, 0x00, 0x00, 0x00, 0x00, // SETARG 0 (handle -> a0)
        0x02, 0x01, 0x00, 0x00, 0x00, // SCONST 1 ("hi there")
        0x0A, 0x01, 0x00, 0x00, 0x00, // SETARG 1 (ptr -> a1)
        0x01, 0x08, 0x00, 0x00, 0x00, // ICONST 8 (len)
        0x09, 0x01, 0x00, 0x00, 0x00, // CALL_IMPORT 1 (setText)
        0x00                          // HALT
    };
    TEST_ASSERT_EQUAL_INT((int)sizeof(expected), buffer->size);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, buffer->code, sizeof(expected));
    // The nested-arg spill reserved one temp local.
    TEST_ASSERT_TRUE(buffer->local_count >= 1);

    codegen_li_free_context(buffer);
}

// Phase 12 (P12-F): MULTIPLE nested handle args (lifts the Phase-11 one-leading-nested
// limit). appendChild(getElementById(…), createElement(…)) — each nested result is
// spilled to its own temp local, then both load back during staging.
void test_frontend_interop_nested_handle_args(void) {
    const char* src =
        "@dom.appendChild(@dom.getElementById(\"out\"), @dom.createElement(\"span\"));\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // Three dom imports auto-registered.
    TEST_ASSERT_EQUAL_INT(3, buffer->import_count);
    TEST_ASSERT_EQUAL_STRING("getElementById", buffer->imports[0].name);
    TEST_ASSERT_EQUAL_STRING("createElement", buffer->imports[1].name);
    TEST_ASSERT_EQUAL_STRING("appendChild", buffer->imports[2].name);

    // Two nested results => at least two temp locals.
    TEST_ASSERT_TRUE(buffer->local_count >= 2);

    // Two STORE_LOCALs (one per nested result) and (≥2) LOAD_LOCALs to stage them.
    int n_store_local = 0, n_load_local = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_STORE_LOCAL) n_store_local++;
        if (buffer->code[i] == OP_LOAD_LOCAL) n_load_local++;
    }
    TEST_ASSERT_EQUAL_INT(2, n_store_local);
    TEST_ASSERT_TRUE(n_load_local >= 2);

    // Through the bridge: distinct temps $v0 and $v1 declared, appendChild call present.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_nested.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(16384);
    memset(out, 0, 16384);
    size_t n = fread(out, 1, 16383, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(local $v0 i32)"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(local $v1 i32)"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $import_2"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 11 (Browser FFI frontend FE-F): event handlers from source. A `fn` handler
// becomes a table routine; @dom.on(elem, "click", handler) registers it (the handler
// name resolves to its table slot). Asserts imports, the main-level on() call with the
// fn-ref, and the routine body (param stash/load + setText).
void test_frontend_interop_event_handler(void) {
    const char* src =
        "fn onClick(target) {\n"
        "  @dom.setText(target, \"hit\");\n"
        "}\n"
        "@dom.on(@dom.getElementById(\"count\"), \"click\", onClick);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // dom imports: getElementById (#0), on (#1), setText (#2).
    TEST_ASSERT_EQUAL_INT(3, buffer->import_count);
    TEST_ASSERT_EQUAL_STRING("getElementById", buffer->imports[0].name);
    TEST_ASSERT_EQUAL_STRING("on", buffer->imports[1].name);
    TEST_ASSERT_EQUAL_INT(4, buffer->imports[1].n_params);
    TEST_ASSERT_EQUAL_STRING("setText", buffer->imports[2].name);

    // The IL must contain a function boundary (the handler routine) and the handler's
    // table slot (0) referenced as an immediate by the on() call.
    int saw_func_begin = 0, saw_func_end = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_FUNC_BEGIN) saw_func_begin = 1;
        if (buffer->code[i] == OP_FUNC_END) saw_func_end = 1;
    }
    TEST_ASSERT_TRUE(saw_func_begin);
    TEST_ASSERT_TRUE(saw_func_end);

    // Through the bridge: the module exports teko_invoke (JS->Teko) and a table, plus
    // the dom.on import and a $routine_0 with a setText call.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_events_src.wat";
    const char* glue = "output_events_src.glue.mjs";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, glue, NULL, NULL, NULL, 0));

    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(32768);
    memset(out, 0, 32768);
    size_t n = fread(out, 1, 32767, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"dom\" \"on\""));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_invoke (export \"teko_invoke\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $routine_0"));
    char* routine = strstr(out, "(func $routine_0");
    TEST_ASSERT_NOT_NULL(strstr(routine, "call $import_2")); // setText inside the handler
    free(out);
    remove(wat);

    // The glue exposes the dom.on listener wiring (addEventListener -> teko_invoke).
    FILE* gf = fopen(glue, "r");
    TEST_ASSERT_NOT_NULL(gf);
    char* g = (char*)malloc(8192);
    memset(g, 0, 8192);
    size_t gn = fread(g, 1, 8191, gf); g[gn] = '\0'; fclose(gf);
    TEST_ASSERT_NOT_NULL(strstr(g, "addEventListener(str(p, n), () => invoke(fn, h))"));
    free(g);
    remove(glue);

    codegen_li_free_context(buffer);
}

// Phase 12 (P12-D): named local variables. `let x = 42; sink(x)` lowers the binding
// to a named local ($v0) via STORE_LOCAL and reads it back via LOAD_LOCAL.
void test_frontend_interop_named_locals(void) {
    const char* src =
        "extern fn sink(n) from \"env\" as \"sink\";\n"
        "let x = 42;\n"
        "sink(x);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // One named local declared.
    TEST_ASSERT_EQUAL_INT(1, buffer->local_count);

    // IL: ICONST 42 -> STORE_LOCAL 0 -> (call: LOAD_LOCAL 0 -> CALL_IMPORT 0) -> HALT.
    const unsigned char expected[] = {
        0x01, 0x2A, 0x00, 0x00, 0x00, // ICONST 42
        0x0C, 0x00, 0x00, 0x00, 0x00, // STORE_LOCAL 0
        0x0B, 0x00, 0x00, 0x00, 0x00, // LOAD_LOCAL 0
        0x09, 0x00, 0x00, 0x00, 0x00, // CALL_IMPORT 0 (sink)
        0x00                          // HALT
    };
    TEST_ASSERT_EQUAL_INT((int)sizeof(expected), buffer->size);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, buffer->code, sizeof(expected));

    // Through the bridge: $main declares $v0 and uses local.set/get $v0.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_locals.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(16384);
    memset(out, 0, 16384);
    size_t n = fread(out, 1, 16383, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(local $v0 i32)"));
    TEST_ASSERT_NOT_NULL(strstr(out, "local.set $v0"));
    TEST_ASSERT_NOT_NULL(strstr(out, "local.get $v0"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 12 (P12-E): integer expressions in `let` initializers. `(6*7)%50` lowers via
// the Pratt parser spilling operands to temp locals; result stored to the named local.
void test_frontend_interop_expressions(void) {
    const char* src =
        "extern fn sink(n) from \"env\" as \"sink\";\n"
        "let r = (6 * 7) % 50;\n"
        "sink(r);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // r is $v0; the expression uses at least one temp local above it.
    TEST_ASSERT_TRUE(buffer->local_count >= 2);

    // The IL contains MUL and MOD opcodes, and STORE_LOCAL/LOAD_LOCAL spills.
    int saw_mul = 0, saw_mod = 0, saw_store_local = 0, saw_load_local = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_MUL) saw_mul = 1;
        if (buffer->code[i] == OP_MOD) saw_mod = 1;
        if (buffer->code[i] == OP_STORE_LOCAL) saw_store_local = 1;
        if (buffer->code[i] == OP_LOAD_LOCAL) saw_load_local = 1;
    }
    TEST_ASSERT_TRUE(saw_mul);
    TEST_ASSERT_TRUE(saw_mod);
    TEST_ASSERT_TRUE(saw_store_local);
    TEST_ASSERT_TRUE(saw_load_local);

    // Through the bridge: the WAT carries the arithmetic + guarded modulo + temp locals.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_expr.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(16384);
    memset(out, 0, 16384);
    size_t n = fread(out, 1, 16383, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "i32.mul"));
    TEST_ASSERT_NOT_NULL(strstr(out, "i32.rem_s"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(local $v1 i32)")); // a temp above $v0
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 12 (P12-G): base64/hex encode+decode are functional. The frontend lowers
// base64.encode/.decode and hex.encode/.decode to OP_CALL_RUNTIME against the native
// codec runtime; this golden pins the lowering + that the codec runtime is emitted.
void test_frontend_interop_base_encoding(void) {
    const char* src =
        "extern fn emit(s) from \"env\" as \"emit\";\n"
        "emit(base64.encode(\"Man\"));\n"
        "emit(hex.decode(\"4d616e\"));\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_codec);

    // Two OP_CALL_RUNTIME ops: codec id 0 (base64 encode) and 3 (hex decode).
    int n_runtime = 0, saw_b64e = 0, saw_hexd = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_CALL_RUNTIME) {
            n_runtime++;
            int id = (int)buffer->code[i + 1]; // 4-byte LE arg; low byte is the id
            if (id == 0) saw_b64e = 1;
            if (id == 3) saw_hexd = 1;
        }
    }
    TEST_ASSERT_EQUAL_INT(2, n_runtime);
    TEST_ASSERT_TRUE(saw_b64e);
    TEST_ASSERT_TRUE(saw_hexd);

    // Through the bridge: the native codec runtime + the calls are emitted.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_codec.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(32768);
    memset(out, 0, 32768);
    size_t n = fread(out, 1, 32767, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_base64_encode (export \"teko_base64_encode\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_hex_decode (export \"teko_hex_decode\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_base64_encode"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_hex_decode"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 13.1: hash.sha256(x) lowers like a codec — OP_CALL_RUNTIME id 4 — and the
// bridge emits the in-module SHA-256 runtime + the shared common helpers, gated on
// buffer->uses_hash (not uses_codec, so codec-free programs stay lean).
void test_frontend_interop_hash_sha256(void) {
    const char* src =
        "extern fn emit(s) from \"env\" as \"emit\";\n"
        "emit(hash.sha256(\"abc\"));\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // Hash flag set; codec flag untouched (no base64/hex used here).
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_hash);
    TEST_ASSERT_EQUAL_INT(0, buffer->uses_codec);

    int n_runtime = 0, saw_sha256 = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_CALL_RUNTIME) {
            n_runtime++;
            int id = (int)buffer->code[i + 1]; // 4-byte LE arg; low byte is the id
            if (id == 4) saw_sha256 = 1;
        }
    }
    TEST_ASSERT_EQUAL_INT(1, n_runtime);
    TEST_ASSERT_TRUE(saw_sha256);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_hash.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_sha256_hex (export \"teko_sha256_hex\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_sha256_hex"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_strlen"));   // shared common runtime
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_hexc"));     // shared common runtime
    TEST_ASSERT_NULL(strstr(out, "$teko_base64_encode"));      // codec runtime omitted
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 13 (legacy): hash.md5 / hash.sha1 lower to OP_CALL_RUNTIME ids 6 / 7 and the bridge
// emits the in-module MD5 + SHA-1 WAT runtimes.
void test_frontend_interop_hash_legacy(void) {
    const char* src =
        "extern fn emit(s) from \"env\" as \"emit\";\n"
        "emit(hash.md5(\"abc\"));\n"
        "emit(hash.sha1(\"abc\"));\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_hash);

    int saw_md5 = 0, saw_sha1 = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_CALL_RUNTIME) {
            int id = (int)buffer->code[i + 1];
            if (id == 6) saw_md5 = 1;
            if (id == 7) saw_sha1 = 1;
        }
    }
    TEST_ASSERT_TRUE(saw_md5);
    TEST_ASSERT_TRUE(saw_sha1);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_hash_legacy.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(131072);
    memset(out, 0, 131072);
    size_t n = fread(out, 1, 131071, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_md5_hex (export \"teko_md5_hex\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_sha1_hex (export \"teko_sha1_hex\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_md5_hex"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_sha1_hex"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 13: uuid.v3 / uuid.v5 lower to OP_CALL_RUNTIME ids 8 / 9 and the bridge emits the
// in-module UUID runtime (built on the MD5/SHA-1 raw cores + the fmt helper).
void test_frontend_interop_uuid(void) {
    const char* src =
        "extern fn emit(s) from \"env\" as \"emit\";\n"
        "emit(uuid.v5(\"python.org\"));\n"
        "emit(uuid.v3(\"python.org\"));\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_hash);

    int saw_v3 = 0, saw_v5 = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_CALL_RUNTIME) {
            int id = (int)buffer->code[i + 1];
            if (id == 8) saw_v3 = 1;
            if (id == 9) saw_v5 = 1;
        }
    }
    TEST_ASSERT_TRUE(saw_v3);
    TEST_ASSERT_TRUE(saw_v5);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_uuid.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(262144);
    memset(out, 0, 262144);
    size_t n = fread(out, 1, 262143, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_uuid_v5 (export \"teko_uuid_v5\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_uuid_v3 (export \"teko_uuid_v3\")"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_uuid_fmt"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_sha1_raw"));   // raw cores feed UUID
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $teko_md5_raw"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 11 (Browser FFI frontend FE-A): import table dedup + interop emit helpers.
// Models the IL a parser would emit for `log("hi")` where
// `extern fn log(msg) from "env" as "log"`: SCONST &"hi" -> CALL_IMPORT #0 -> HALT.
void test_codegen_li_import_table_and_interop_emit(void) {
    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);

    // Import table dedup by (ns, name).
    int i0 = codegen_li_add_import(buffer, "env", "log", 1, 0);
    int i1 = codegen_li_add_import(buffer, "env", "log", 1, 0); // duplicate
    int i2 = codegen_li_add_import(buffer, "dom", "setText", 3, 0);
    TEST_ASSERT_EQUAL_INT(0, i0);
    TEST_ASSERT_EQUAL_INT(0, i1);
    TEST_ASSERT_EQUAL_INT(1, i2);
    TEST_ASSERT_EQUAL_INT(2, buffer->import_count);
    TEST_ASSERT_EQUAL_STRING("env", buffer->imports[0].ns);
    TEST_ASSERT_EQUAL_STRING("log", buffer->imports[0].name);
    TEST_ASSERT_EQUAL_INT(1, buffer->imports[0].n_params);
    TEST_ASSERT_EQUAL_INT(0, buffer->imports[0].has_result);

    // Emit: SCONST &"hi" (pool 0) -> CALL_IMPORT #0 -> HALT.
    int s = codegen_li_add_string_constant(buffer, "hi");
    TEST_ASSERT_EQUAL_INT(0, s);
    codegen_li_emit_sconst(buffer, s);
    codegen_li_emit_call_import(buffer, i0);
    codegen_li_emit_halt(buffer);

    // Expected bytes: 0x02 00000000 | 0x09 00000000 | 0x00
    TEST_ASSERT_EQUAL_INT(11, buffer->size);
    const unsigned char expected[] = {
        0x02, 0x00, 0x00, 0x00, 0x00, // OP_SCONST 0
        0x09, 0x00, 0x00, 0x00, 0x00, // OP_CALL_IMPORT 0
        0x00                          // OP_HALT
    };
    TEST_ASSERT_EQUAL_UINT8_ARRAY(expected, buffer->code, sizeof(expected));

    // setarg/iconst/func_begin/func_end helpers emit the right opcodes too.
    int before = buffer->size;
    codegen_li_emit_setarg(buffer, 2);
    TEST_ASSERT_EQUAL_UINT8(OP_SETARG, buffer->code[before]);
    TEST_ASSERT_EQUAL_UINT8(2, buffer->code[before + 1]);
    int b2 = buffer->size;
    codegen_li_emit_func_begin(buffer, 0);
    codegen_li_emit_func_end(buffer);
    TEST_ASSERT_EQUAL_UINT8(OP_FUNC_BEGIN, buffer->code[b2]);
    TEST_ASSERT_EQUAL_UINT8(OP_FUNC_END, buffer->code[b2 + 5]);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.A): a `routines { … }` block fires each enclosed call as a background task.
// The frontend lowers it to ICONST <slot> + OP_SPAWN_ASYNC (per call), sets uses_spawn, and
// emits the named `fn` as a table routine. The WASM bridge then drains the cooperative
// scheduler at $main close (`call $teko_sched_run`) so the tasks run before exit.
void test_frontend_interop_routines_spawn(void) {
    const char* src =
        "extern fn log(msg: str) from \"env\" as \"log\";\n"
        "fn worker() { log(\"worker ran\"); }\n"
        "log(\"main start\");\n"
        "routines { worker(); worker(); }\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    // Firing a routine sets the spawn flag and lowers to OP_SPAWN_ASYNC + a table routine.
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_spawn);
    int spawns = 0, func_begins = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_SPAWN_ASYNC) spawns++;
        else if (buffer->code[i] == OP_FUNC_BEGIN) func_begins++;
    }
    TEST_ASSERT_EQUAL_INT(2, spawns);       // two worker() calls fired
    TEST_ASSERT_EQUAL_INT(1, func_begins);  // one `fn worker` emitted as a routine

    // Through the WASM bridge: the routine body, the scheduler drain at $main close, and a
    // function table with the routine must all be present.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_routines.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));

    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(func $routine_0"));        // worker lowered to a routine
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_enqueue"));      // spawn enqueues the task
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_sched_run"));    // drained before $main returns
    TEST_ASSERT_NOT_NULL(strstr(out, "(elem (i32.const 0) $routine_0"));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.B): `duplex.*` dotted-identifier calls lower to the dedicated OP_DUPLEX_*
// opcodes (not OP_CALL_RUNTIME), set uses_duplex, and stage multi-arg ops via OP_SETARG.
void test_frontend_interop_duplex_lowering(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "let h = duplex.open(4);\n"
        "duplex.send(h, 0, 111);\n"
        "let a = duplex.recv(h, 1);\n"
        "emit_int(a);\n"
        "duplex.close(h);\n"
        "let s = duplex.poll(h, 1);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_duplex);
    int n_open = 0, n_send = 0, n_recv = 0, n_poll = 0, n_close = 0;
    for (int i = 0; i < buffer->size; i++) {
        switch (buffer->code[i]) {
            case OP_DUPLEX_OPEN:  n_open++;  break;
            case OP_DUPLEX_SEND:  n_send++;  break;
            case OP_DUPLEX_RECV:  n_recv++;  break;
            case OP_DUPLEX_POLL:  n_poll++;  break;
            case OP_DUPLEX_CLOSE: n_close++; break;
            default: break;
        }
    }
    TEST_ASSERT_EQUAL_INT(1, n_open);
    TEST_ASSERT_EQUAL_INT(1, n_send);
    TEST_ASSERT_EQUAL_INT(1, n_recv);
    TEST_ASSERT_EQUAL_INT(1, n_poll);
    TEST_ASSERT_EQUAL_INT(1, n_close);

    // Through the WASM bridge: the duplex ops import the reactor entry points + share memory.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_duplex.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"crypto\" \"teko_rt_duplex_open\""));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $duplex_send"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $duplex_poll"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"memory\"")); // shared with the reactor
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.C): `delayed.*` dotted-identifier calls lower to the dedicated OP_DELAYED_*
// opcodes, set uses_delayed, and (on WASM) import the reactor entry points over shared memory.
void test_frontend_interop_delayed_lowering(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "let d = delayed.open(8);\n"
        "delayed.send(d, 10, 10);\n"
        "let a = delayed.recv(d);\n"
        "emit_int(a);\n"
        "let p = delayed.poll(d);\n"
        "delayed.close(d);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_delayed);
    int n_open = 0, n_send = 0, n_recv = 0, n_poll = 0, n_close = 0;
    for (int i = 0; i < buffer->size; i++) {
        switch (buffer->code[i]) {
            case OP_DELAYED_OPEN:    n_open++;  break;
            case OP_DELAYED_SEND:    n_send++;  break;
            case OP_DELAYED_RECV:    n_recv++;  break;
            case OP_DELAYED_POLL:    n_poll++;  break;
            case OP_DELAYED_CLOSE:   n_close++; break;
            default: break;
        }
    }
    TEST_ASSERT_EQUAL_INT(1, n_open);
    TEST_ASSERT_EQUAL_INT(1, n_send);
    TEST_ASSERT_EQUAL_INT(1, n_recv);
    TEST_ASSERT_EQUAL_INT(1, n_poll);
    TEST_ASSERT_EQUAL_INT(1, n_close);

    // Through the WASM bridge: the delayed ops import the reactor entry points + share memory.
    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_delayed.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"crypto\" \"teko_rt_delayed_open\""));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $delayed_recv"));
    TEST_ASSERT_NULL(strstr(out, "delayed_advance")); // logical advance removed (real-time clock)
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"memory\""));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.D): `broadcast.*` dotted-identifier calls lower to OP_BCAST_*, set uses_bcast,
// and (on WASM) import the reactor entry points over shared memory.
void test_frontend_interop_broadcast_lowering(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "let b = broadcast.open(8);\n"
        "let s = broadcast.subscribe(b);\n"
        "broadcast.publish(b, 10);\n"
        "let a = broadcast.recv(b, s);\n"
        "emit_int(a);\n"
        "let p = broadcast.poll(b, s);\n"
        "broadcast.close(b);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_bcast);
    int n_open=0,n_sub=0,n_pub=0,n_recv=0,n_poll=0,n_close=0;
    for (int i = 0; i < buffer->size; i++) {
        switch (buffer->code[i]) {
            case OP_BCAST_OPEN:      n_open++;  break;
            case OP_BCAST_SUBSCRIBE: n_sub++;   break;
            case OP_BCAST_PUBLISH:   n_pub++;   break;
            case OP_BCAST_RECV:      n_recv++;  break;
            case OP_BCAST_POLL:      n_poll++;  break;
            case OP_BCAST_CLOSE:     n_close++; break;
            default: break;
        }
    }
    TEST_ASSERT_EQUAL_INT(1, n_open);
    TEST_ASSERT_EQUAL_INT(1, n_sub);
    TEST_ASSERT_EQUAL_INT(1, n_pub);
    TEST_ASSERT_EQUAL_INT(1, n_recv);
    TEST_ASSERT_EQUAL_INT(1, n_poll);
    TEST_ASSERT_EQUAL_INT(1, n_close);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_broadcast.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"crypto\" \"teko_rt_bcast_subscribe\""));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $bcast_publish"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"memory\""));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.E): a `shared { }` block injects OP_SHARED_ENTER/LEAVE around its body; `atomic.*`
// lower to OP_ATOMIC_*. Sets uses_shared; WASM imports the reactor entry points over shared memory.
void test_frontend_interop_shared_lowering(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "let c = atomic.cell(0);\n"
        "shared {\n"
        "  atomic.add(c, 5);\n"
        "  atomic.add(c, 3);\n"
        "}\n"
        "let v = atomic.load(c);\n"
        "emit_int(v);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_shared);
    int n_enter=0,n_leave=0,n_cell=0,n_add=0,n_load=0;
    for (int i = 0; i < buffer->size; i++) {
        switch (buffer->code[i]) {
            case OP_SHARED_ENTER: n_enter++; break;
            case OP_SHARED_LEAVE: n_leave++; break;
            case OP_ATOMIC_CELL:  n_cell++;  break;
            case OP_ATOMIC_ADD:   n_add++;   break;
            case OP_ATOMIC_LOAD:  n_load++;  break;
            default: break;
        }
    }
    TEST_ASSERT_EQUAL_INT(1, n_enter);  // one shared block
    TEST_ASSERT_EQUAL_INT(1, n_leave);
    TEST_ASSERT_EQUAL_INT(1, n_cell);
    TEST_ASSERT_EQUAL_INT(2, n_add);    // two atomic.add inside the block
    TEST_ASSERT_EQUAL_INT(1, n_load);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_shared.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"crypto\" \"teko_atomic_add\""));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $shared_enter"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $shared_leave"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"memory\""));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.G): timespan literals carrying a time-unit suffix normalize to canonical
// milliseconds at compile time, so the integer-only channel/delay runtimes stay unchanged.
// `2s` → ICONST 2000, `1m` → 60000, `500ms` → 500; a unit-less value passes through.
static int il_has_iconst(const BytecodeBuffer* b, int value) {
    for (int i = 0; i + 4 < b->size; i++) {
        if (b->code[i] == OP_ICONST) {
            int v = (int)((unsigned)b->code[i+1] | ((unsigned)b->code[i+2] << 8) |
                          ((unsigned)b->code[i+3] << 16) | ((unsigned)b->code[i+4] << 24));
            if (v == value) return 1;
        }
    }
    return 0;
}

// Phase 14 (14.G): `wait <ts>;` / `await <ts>;` lower to OP_WAIT / OP_AWAIT_FOR with the timespan
// normalized to canonical ms in the preceding ICONST. await sets uses_await + uses_spawn; wait
// sets uses_wait. On WASM the host sleep/await imports are declared + (await) the scheduler drains.
void test_frontend_interop_waiters_lowering(void) {
    const char* src =
        "wait 2s;\n"     // 2s   -> ICONST 2000 ; OP_WAIT
        "await 5ms;\n";  // 5ms  -> ICONST 5    ; OP_AWAIT_FOR

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_wait);
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_await);
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_spawn); // await emits the native routine table
    int n_wait = 0, n_await = 0;
    for (int i = 0; i < buffer->size; i++) {
        if (buffer->code[i] == OP_WAIT) n_wait++;
        if (buffer->code[i] == OP_AWAIT_FOR) n_await++;
    }
    TEST_ASSERT_EQUAL_INT(1, n_wait);
    TEST_ASSERT_EQUAL_INT(1, n_await);
    TEST_ASSERT_TRUE(il_has_iconst(buffer, 2000)); // 2s normalized for wait
    TEST_ASSERT_TRUE(il_has_iconst(buffer, 5));    // 5ms for await

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_waiters.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    // Real-time clock: waiters import the host monotonic ns clock and spin to a real deadline.
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"teko_now_ns\" (func $teko_now_ns (result i64)))"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_now_ns"));   // deadline read + spin check
    TEST_ASSERT_NOT_NULL(strstr(out, "i64.ge_u"));            // real-time deadline comparison
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_sched_run")); // await drains the scheduler
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (control-flow foundation): `while`/`loop`/`if`/`break`/`continue` + reassignment lower
// to the structured OP_LOOP_*/OP_IF_*/OP_BREAK* opcodes; on WASM to (block $brk (loop $cont …)) +
// (if … end). Pins the opcode set in the IL and the structured forms in the emitted .wat.
void test_frontend_interop_controlflow_lowering(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "let i = 0;\n"
        "while (i < 3) { i = i + 1; }\n"
        "loop { if (i >= 5) { break; } i = i + 1; }\n"
        "emit_int(i);\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    int n_lbeg=0,n_lend=0,n_break=0,n_bif=0,n_ifb=0,n_ife=0;
    for (int i = 0; i < buffer->size; i++) {
        switch (buffer->code[i]) {
            case OP_LOOP_BEGIN:     n_lbeg++;  break;
            case OP_LOOP_END:       n_lend++;  break;
            case OP_BREAK:          n_break++; break;
            case OP_BREAK_IF_FALSE: n_bif++;   break;
            case OP_IF_BEGIN:       n_ifb++;   break;
            case OP_IF_END:         n_ife++;   break;
            default: break;
        }
    }
    TEST_ASSERT_EQUAL_INT(2, n_lbeg);   // while + loop
    TEST_ASSERT_EQUAL_INT(2, n_lend);
    TEST_ASSERT_EQUAL_INT(1, n_bif);    // while condition
    TEST_ASSERT_EQUAL_INT(1, n_break);  // break inside loop
    TEST_ASSERT_EQUAL_INT(1, n_ifb);    // if
    TEST_ASSERT_EQUAL_INT(1, n_ife);

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_controlflow.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(block $brk_0 (loop $cont_0"));
    TEST_ASSERT_NOT_NULL(strstr(out, "br_if $brk_0"));   // while condition test
    TEST_ASSERT_NOT_NULL(strstr(out, "br $cont_0"));     // back-edge
    TEST_ASSERT_NOT_NULL(strstr(out, "br $brk_1"));      // break in the second loop
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.H capstone enabler): a routine body can now contain control flow + named locals
// (the shared block-body dispatcher), so a background `fn` worker can run a `while` loop. Pins a
// loop (OP_LOOP_BEGIN) emitted inside a routine function (after the OP_FUNC_BEGIN), with the
// routine fired via `routines { }` (OP_SPAWN_ASYNC).
void test_frontend_interop_routine_loop(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "fn worker() { let w = 0; while (w < 3) { w = w + 1; emit_int(w); } }\n"
        "routines { worker(); }\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_spawn);

    // Find the routine's OP_FUNC_BEGIN, then assert an OP_LOOP_BEGIN follows it (a loop inside
    // the routine body). Walk opcodes honoring 4-byte-arg ops so arg bytes aren't misread.
    int func_at = -1, loop_after_func = 0;
    for (int i = 0; i < buffer->size; ) {
        unsigned char op = buffer->code[i];
        if (op == OP_FUNC_BEGIN) func_at = i;
        if (op == OP_LOOP_BEGIN && func_at >= 0) loop_after_func = 1;
        if (op == OP_ICONST || op == OP_SCONST || op == OP_JMP || op == OP_JMP_IF_FALSE ||
            op == OP_FUNC_BEGIN || op == OP_CALL_IMPORT || op == OP_SETARG ||
            op == OP_LOAD_LOCAL || op == OP_STORE_LOCAL || op == OP_CALL_RUNTIME) i += 5;
        else i += 1;
    }
    TEST_ASSERT_TRUE(func_at >= 0);     // worker emitted as a routine function
    TEST_ASSERT_TRUE(loop_after_func);  // with a while-loop inside it

    codegen_li_free_context(buffer);
}

// Phase 14 (14.I): `routines { worker(a, b); }` passes N arguments (Go-style) — each staged via
// OP_SETARG, then OP_SPAWN_ASYNC_ARGS argc. The routine `fn worker(a, b)` binds each param from
// OP_LOAD_SPAWN_ARG i. Pins the multi-arg spawn + per-param load in the IL, and the WASM frame ops.
void test_frontend_interop_routine_args(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "fn worker(a, b) { let s = a + b; emit_int(s); }\n"
        "let x = 3;\n"
        "let y = 4;\n"
        "routines { worker(x, y); }\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));
    TEST_ASSERT_EQUAL_INT(1, buffer->uses_spawn);

    int n_spawn_args = 0, spawn_argc = -1, n_load0 = 0, n_load1 = 0;
    for (int i = 0; i + 4 < buffer->size; ) {
        unsigned char op = buffer->code[i];
        int a = (int)((unsigned)buffer->code[i+1] | ((unsigned)buffer->code[i+2] << 8) |
                      ((unsigned)buffer->code[i+3] << 16) | ((unsigned)buffer->code[i+4] << 24));
        if (op == OP_SPAWN_ASYNC_ARGS) { n_spawn_args++; spawn_argc = a; }
        if (op == OP_LOAD_SPAWN_ARG && a == 0) n_load0++;
        if (op == OP_LOAD_SPAWN_ARG && a == 1) n_load1++;
        if (op == OP_ICONST || op == OP_SCONST || op == OP_JMP || op == OP_JMP_IF_FALSE ||
            op == OP_FUNC_BEGIN || op == OP_CALL_IMPORT || op == OP_SETARG ||
            op == OP_LOAD_LOCAL || op == OP_STORE_LOCAL || op == OP_CALL_RUNTIME ||
            op == OP_SPAWN_ASYNC_ARGS || op == OP_LOAD_SPAWN_ARG) i += 5;
        else i += 1;
    }
    TEST_ASSERT_EQUAL_INT(1, n_spawn_args);   // one multi-arg spawn
    TEST_ASSERT_EQUAL_INT(2, spawn_argc);     // worker(x, y) -> argc 2
    TEST_ASSERT_EQUAL_INT(1, n_load0);        // param a <- arg 0
    TEST_ASSERT_EQUAL_INT(1, n_load1);        // param b <- arg 1

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_routineargs.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "call $teko_enqueue"));  // spawn-with-args enqueues a task
    TEST_ASSERT_NOT_NULL(strstr(out, "local.get $frame"));    // param bound from the task frame
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

// Phase 14 (14.F): the `retry { } fallback { }` and `circuit cb { } fallback { }` blocks lower to
// the policy opcodes OP_RETRY_*/OP_CIRCUIT_* (driving the teko_retry C runtime) wrapped in the
// control-flow foundation; set uses_retry; on WASM import the reactor policy entry points.
void test_frontend_interop_resilience_lowering(void) {
    const char* src =
        "extern fn emit_int(n: i32) from \"teko_rt\" as \"teko_rt_emit_int\";\n"
        "let t = 0;\n"
        "retry (attempts 3, exponential, base 1) { t = t + 1; t >= 2; } fallback { emit_int(9); }\n"
        "let cb = circuit(threshold 2, cooldown 50);\n" // 50 avoids the 0x62-0x67 opcode byte range
        "circuit cb { 0; } fallback { emit_int(8); }\n";

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_EQUAL_INT(1, buffer->uses_retry);
    int n_rnew=0,n_sc=0,n_nd=0,n_cnew=0,n_callow=0,n_crec=0;
    for (int i = 0; i < buffer->size; i++) {
        switch (buffer->code[i]) {
            case OP_RETRY_NEW:             n_rnew++;   break;
            case OP_RETRY_SHOULD_CONTINUE: n_sc++;     break;
            case OP_RETRY_NEXT_DELAY:      n_nd++;     break;
            case OP_CIRCUIT_NEW:           n_cnew++;   break;
            case OP_CIRCUIT_ALLOW:         n_callow++; break;
            case OP_CIRCUIT_RECORD:        n_crec++;   break;
            default: break;
        }
    }
    TEST_ASSERT_EQUAL_INT(1, n_rnew);    // one retry policy
    TEST_ASSERT_EQUAL_INT(1, n_sc);      // the should-continue gate
    TEST_ASSERT_EQUAL_INT(1, n_nd);      // the backoff next-delay
    TEST_ASSERT_EQUAL_INT(1, n_cnew);    // the circuit constructor
    TEST_ASSERT_EQUAL_INT(1, n_callow);  // the breaker guard
    TEST_ASSERT_EQUAL_INT(1, n_crec);    // the outcome record

    TekoTarget target;
    target.arch = ARCH_WASM32;
    target.os = OS_WASI;
    strncpy(target.target_string, "wasm32-wasi", sizeof(target.target_string) - 1);
    const char* wat = "output_interop_resilience.wat";
    TEST_ASSERT_EQUAL_INT(0, codegen_li_emit_wasm(buffer, wat, target, NULL, NULL, NULL, NULL, 0));
    FILE* f = fopen(wat, "r");
    TEST_ASSERT_NOT_NULL(f);
    char* out = (char*)malloc(65536);
    memset(out, 0, 65536);
    size_t n = fread(out, 1, 65535, f); out[n] = '\0'; fclose(f);
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"crypto\" \"teko_rt_retry_new\""));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $retry_should_continue"));
    TEST_ASSERT_NOT_NULL(strstr(out, "call $circuit_allow"));
    TEST_ASSERT_NOT_NULL(strstr(out, "(import \"env\" \"memory\""));
    free(out);
    remove(wat);

    codegen_li_free_context(buffer);
}

void test_frontend_interop_timespan_normalization(void) {
    const char* src =
        "let d = delayed.open(8);\n"
        "delayed.send(d, 7, 2s);\n"     // 2s   -> 2000 ms; value 7 unchanged
        "delayed.send(d, 8, 500ms);\n"  // 500ms-> 500 ms
        "delayed.send(d, 9, 1m);\n";    // 1m   -> 60000 ms

    BytecodeBuffer* buffer = codegen_li_create_context();
    TEST_ASSERT_NOT_NULL(buffer);
    TEST_ASSERT_EQUAL_INT(0, teko_compile_interop(src, buffer));

    TEST_ASSERT_TRUE(il_has_iconst(buffer, 2000));  // 2s normalized
    TEST_ASSERT_TRUE(il_has_iconst(buffer, 500));   // 500ms
    TEST_ASSERT_TRUE(il_has_iconst(buffer, 60000)); // 1m
    TEST_ASSERT_TRUE(il_has_iconst(buffer, 7));     // unit-less value unchanged

    codegen_li_free_context(buffer);
}
