;;; teko-mode.el --- major mode for the Teko language -*- lexical-binding: t; -*-

;; GENERATED by tooling/emacs (A4); do not edit by hand.
;; Regenerate: tooling/emacs/bin/teko_grammar_gen_emacs [repo-root]

(defconst teko-font-lock-keywords
  (list
   (cons "\\_<\\(interface\\|abstract\\|continue\\|override\\|variant\\|virtual\\|extern\\|intern\\|return\\|struct\\|break\\|class\\|const\\|defer\\|false\\|flags\\|match\\|else\\|enum\\|loop\\|null\\|true\\|type\\|when\\|exp\\|let\\|mut\\|pub\\|use\\|as\\|fn\\|if\\|in\\|to\\)\\_>" font-lock-keyword-face)
   (cons "<<=\\|>>=\\|\\.\\.=\\|==\\|=>\\|!=\\|<=\\|>=\\|<<\\|>>\\|->\\|::\\|&&\\|||\\|\\+\\+\\|--\\|\\+=\\|-=\\|\\*=\\|/=\\|%=\\|&=\\||=\\|\\^=\\|\\?\\?\\|\\?\\.\\|\\.\\.\\|\\+\\|-\\|\\*\\|/\\|%\\|&\\||\\|\\^\\|~\\|!\\|<\\|>\\|=\\|:\\|;\\|,\\|\\.\\|(\\|)\\|{\\|}\\|\\[\\|\\]\\|\\?\\|#" font-lock-builtin-face)
   (cons "\\b0[xX][0-9a-fA-F_]+\\b" font-lock-constant-face)
   (cons "\\b0[bB][01_]+\\b" font-lock-constant-face)
   (cons "\\b[0-9][0-9_]*(\\.[0-9][0-9_]*)?([eE][+-]?[0-9][0-9_]*)?\\b" font-lock-constant-face))
  "Keyword/operator/literal highlighting for `teko-mode`, generated from the compiler's own lexer (see tooling/shared, A1).")

(defvar teko-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?/ "< b" table)
    (modify-syntax-entry ?\n "> b" table)
    (modify-syntax-entry ?" "\"" table)
    table)
  "Syntax table for `teko-mode` (line-comment lead byte + string quote, from tooling/shared's mined spec).")

(define-derived-mode teko-mode prog-mode "Teko"
  "Major mode for editing Teko (.tks/.tkt) source."
  :syntax-table teko-mode-syntax-table
  (setq-local font-lock-defaults '(teko-font-lock-keywords))
  (setq-local comment-start "// ")
  (setq-local comment-end ""))

(add-to-list 'auto-mode-alist '("\\.tks\\'" . teko-mode))
(add-to-list 'auto-mode-alist '("\\.tkt\\'" . teko-mode))
(when (fboundp 'toml-mode) (add-to-list 'auto-mode-alist '("\\.tkp\\'" . toml-mode)))

(provide 'teko-mode)
;;; teko-mode.el ends here
