blank_issues_enabled: true
contact_links:
  - name: Questions & discussion
    url: https://github.com/schivei/teko-lang/discussions
    about: Ask questions or discuss ideas before they become concrete proposals.
