#include "unity.h"
#include "../../src/runtime/teko_decimal.h"
#include "teko_decimal_kat_vectors.h"   // generated by tools/gen_decimal_kats.py
#include <stdint.h>
#include <string.h>
#include <stdio.h>

// Phase 17.F.1 — KATs for the 256-byte exact base-10 decimal runtime core
// (teko_decimal.c). The oracle is Python `decimal` (ROUND_HALF_EVEN, prec>=600); the
// generator (tools/gen_decimal_kats.py) serializes each operand AND the expected result
// into the EXACT 256-byte little-endian teko_decimal encoding. For every vector we run the
// C op and assert: the ok-flag matches expect_ok AND (on ok) memcmp(out, expected, 256)==0.
//
// Everything is deterministic: pure functions, no clock/rand/globals — native == WASM.

// Op tags — MUST match OP_* in gen_decimal_kats.py.
enum { TEKO_DEC_OP_ADD, TEKO_DEC_OP_SUB, TEKO_DEC_OP_MUL,
       TEKO_DEC_OP_DIV, TEKO_DEC_OP_MOD, TEKO_DEC_OP_CMP };

// Run one op given the raw 256-byte operand encodings; write the 256-byte result. Returns
// the op's ok-flag (1/0). For CMP, the result is encoded as a scale-0 decimal in {-1,0,1}.
static int run_op(int op, const teko_decimal* a, const teko_decimal* b, teko_decimal* out) {
    switch (op) {
        case TEKO_DEC_OP_ADD: return teko_decimal_add(a, b, out);
        case TEKO_DEC_OP_SUB: return teko_decimal_sub(a, b, out);
        case TEKO_DEC_OP_MUL: return teko_decimal_mul(a, b, out);
        case TEKO_DEC_OP_DIV: return teko_decimal_div(a, b, out);
        case TEKO_DEC_OP_MOD: return teko_decimal_mod(a, b, out);
        case TEKO_DEC_OP_CMP: {
            int c = 0;
            int ok = teko_decimal_cmp(a, b, &c);
            // Encode {-1,0,1} into a scale-0 decimal the same way the oracle did.
            teko_decimal_zero(out);
            if (c != 0) {
                out->sign = (c < 0) ? 1u : 0u;
                out->limb[0] = 1u;
            }
            return ok;
        }
        default: return 0;
    }
}

void test_teko_decimal_struct_layout(void) {
    TEST_ASSERT_EQUAL_UINT(256, (unsigned)sizeof(teko_decimal));
    TEST_ASSERT_EQUAL_UINT(8, (unsigned)_Alignof(teko_decimal));
    // Field offsets per the locked spec.
    teko_decimal d;
    TEST_ASSERT_EQUAL_PTR((void*)&d.sign,  (void*)((char*)&d + 0));
    TEST_ASSERT_EQUAL_PTR((void*)&d.scale, (void*)((char*)&d + 1));
    TEST_ASSERT_EQUAL_PTR((void*)&d.flags, (void*)((char*)&d + 2));
    TEST_ASSERT_EQUAL_PTR((void*)&d.limb,  (void*)((char*)&d + 8));
}

void test_teko_decimal_from_components(void) {
    teko_decimal d;
    // 12345 @ scale 2 = 123.45
    TEST_ASSERT_EQUAL_INT(1, teko_decimal_from_components(0, 2, "12345", &d));
    TEST_ASSERT_EQUAL_UINT(0, d.sign);
    TEST_ASSERT_EQUAL_UINT(2, d.scale);
    TEST_ASSERT_EQUAL_UINT64(12345ull, d.limb[0]);
    // Leading zeros tolerated; empty/NULL => zero (sign canonicalized).
    TEST_ASSERT_EQUAL_INT(1, teko_decimal_from_components(1, 0, "0", &d));
    TEST_ASSERT_EQUAL_UINT(0, d.sign);
    TEST_ASSERT_EQUAL_UINT64(0ull, d.limb[0]);
    TEST_ASSERT_EQUAL_INT(1, teko_decimal_from_components(0, 5, NULL, &d));
    TEST_ASSERT_EQUAL_UINT64(0ull, d.limb[0]);
    // scale > 38 rejected.
    TEST_ASSERT_EQUAL_INT(0, teko_decimal_from_components(0, 39, "1", &d));
    // 2^64 spans two limbs.
    TEST_ASSERT_EQUAL_INT(1, teko_decimal_from_components(0, 0, "18446744073709551616", &d));
    TEST_ASSERT_EQUAL_UINT64(0ull, d.limb[0]);
    TEST_ASSERT_EQUAL_UINT64(1ull, d.limb[1]);
}

void test_teko_decimal_kat_vectors(void) {
    char msg[128];
    for (size_t i = 0; i < TEKO_DECIMAL_KAT_COUNT; i++) {
        const teko_decimal_kat* k = &TEKO_DECIMAL_KATS[i];
        teko_decimal a, b, out;
        memcpy(&a, k->a, 256);
        memcpy(&b, k->b, 256);
        memset(&out, 0xCD, sizeof(out)); // poison so a no-write is caught
        int ok = run_op(k->op, &a, &b, &out);

        snprintf(msg, sizeof(msg), "vector #%zu (%s): ok-flag", i, k->label);
        TEST_ASSERT_EQUAL_INT_MESSAGE(k->expect_ok, ok, msg);

        if (k->expect_ok) {
            if (memcmp(&out, k->result, 256) != 0) {
                snprintf(msg, sizeof(msg), "vector #%zu (%s): result bytes differ", i, k->label);
                TEST_FAIL_MESSAGE(msg);
            }
        }
    }
}
