#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "project_manager.h"
#include "codegen/codegen_metal.h"
#include "codegen/tld_elf.h"
#include "codegen/tld_elf_arch.h"
#include "codegen/tld_symbols.h"

static uint16_t get_linker_elf_machine(TekoArch arch) {
    switch (arch) {
        case ARCH_X86_64: return 62;
        case ARCH_X86:    return 3;
        case ARCH_ARM64:  return 183;
        case ARCH_ARM32:  return 40;
        default:          return 62;
    }
}

int main(int argc, char** argv) {
    printf("==================================================\n");
    printf(" Teko AOT Compiler Driver - Multi-Mode Pipeline   \n");
    printf("==================================================\n\n");

    if (argc < 2) {
        printf("Usage: teko build <file_or_project> [flags]\n");
        printf("Flags:\n");
        printf("  -S        Stop after generating the assembly text file (.s)\n");
        printf("  -c        Stop after generating the unlinked binary object file (.o)\n");
        return 1;
    }

    const char* input_path = argv[1];
    bool stop_at_assembly = false;
    bool stop_at_object = false;

    for (int i = 2; i < argc; i++) {
        if (strcmp(argv[i], "-S") == 0) stop_at_assembly = true;
        if (strcmp(argv[i], "-c") == 0) stop_at_object = true;
    }

    // DEFAULT HOST TARGET (can be parameterized via a later flag)
    TekoTarget target = { .arch = ARCH_X86_64, .os = OS_LINUX };

    // ====================================================================
    // SPECIAL CASE: The user passed an Assembly file (.s) directly for linking
    // ====================================================================
    if (strstr(input_path, ".s") != NULL) {
        printf("[Teko Pipeline]: Detected external textual assembly file: %s\n", input_path);
        printf("[Teko Linker]: Skipping Frontend. Invoking Native Linker directly...\n");

        // Simulates reading and parsing the .s text back into machine instructions
        // In production, the linker scans the .s generating the real opcode buffer
        uint8_t machine_code_buffer[256];
        uint32_t machine_code_size = 0;

        // Example instructions injected from parsing the .s
        machine_code_size += tld_arch_encode_instruction(target.arch, OP_ICONST, 100, &machine_code_buffer[machine_code_size]);
        machine_code_size += tld_arch_encode_instruction(target.arch, OP_HALT, 0, &machine_code_buffer[machine_code_size]);

        char binary_out[] = "output_from_assembly_exec";
        bool link_success = tld_elf64_write_executable(binary_out, machine_code_buffer, machine_code_size, get_linker_elf_machine(target.arch));

        if (link_success) {
            printf("[Teko Linker]: Binary successfully generated from .s file: %s\n", binary_out);
            return 0;
        }
        return 1;
    }

    // ====================================================================
    // STANDARD PIPELINE: Compilation based on Manifest (.tkp)
    // ====================================================================
    TekoProjectConfig* config = teko_project_load(input_path);
    if (!config || !teko_project_validate_structure(config)) {
        fprintf(stderr, "[Fatal Error]: Failed to validate or read the manifest.\n");
        if (config) teko_project_free(config);
        return 1;
    }

    printf("[Teko Driver]: Processing project '%s'...\n", config->project_name);

    // Mock Intermediate Language (IL) bytecode generated by the Parser
    unsigned char mock_bytecode[] = { 0x01, 0x1F, 0x00, 0x00, 0x00, 0x00 }; // ICONST 31 -> HALT
    uint32_t bytecode_size = sizeof(mock_bytecode);

    // 1. GENERATION OF THE INTERMEDIATE TEXTUAL FILE (.s)
    char asm_output_path[512];
    snprintf(asm_output_path, sizeof(asm_output_path), "%s/%s.s", config->root_dir, config->project_name);

    MetalContext* ctx = teko_metal_create(asm_output_path, target);
    if (ctx) {
        teko_metal_emit_program(ctx, mock_bytecode, bytecode_size);
        teko_metal_close(ctx);
        printf("[Step 1/3 - Codegen]: Intermediate assembly .s file written: %s\n", asm_output_path);
    }

    // INTERRUPTION BY FLAG -S: If the developer requested only the text file, stop here
    if (stop_at_assembly) {
        printf("[Teko Pipeline]: Pipeline halted by -S flag. Finishing.\n");
        teko_project_free(config);
        return 0;
    }

    // 2. TRANSLATION TO UNLINKED BINARY OBJECT FILE (.o)
    uint8_t machine_code_buffer[4096];
    uint32_t machine_code_size = 0;
    uint32_t cursor = 0;

    while (cursor < bytecode_size) {
        OpCode op = (OpCode)mock_bytecode[cursor++];
        int32_t arg = 0;
        if (op == OP_ICONST) {
            arg = mock_bytecode[cursor] | (mock_bytecode[cursor+1] << 8) |
                  (mock_bytecode[cursor+2] << 16) | (mock_bytecode[cursor+3] << 24);
            cursor += 4;
        }
        machine_code_size += tld_arch_encode_instruction(target.arch, op, arg, &machine_code_buffer[machine_code_size]);
    }

    char obj_output_path[512];
    snprintf(obj_output_path, sizeof(obj_output_path), "%s/%s.o", config->root_dir, config->project_name);

    // Write the raw unlinked object file to disk for developer inspection
    FILE* obj_file = fopen(obj_output_path, "wb");
    if (obj_file) {
        fwrite(machine_code_buffer, 1, machine_code_size, obj_file);
        fclose(obj_file);
        printf("[Step 2/3 - Object]: Intermediate binary object .o file written: %s\n", obj_output_path);
    }

    // INTERRUPTION BY FLAG -c: If only the unlinked binary object was requested, stop here
    if (stop_at_object) {
        printf("[Teko Pipeline]: Pipeline halted by -c flag. Finishing.\n");
        teko_project_free(config);
        return 0;
    }

    // 3. FINAL STAGE - GENERATION OF THE FINAL LINKED EXECUTABLE
    char bin_output_path[512];
    bool is_shared = (config->target_type == TARGET_DYNAMIC_LIB);
    snprintf(bin_output_path, sizeof(bin_output_path), "%s/%s%s",
             config->root_dir, config->project_name, is_shared ? ".so" : "");

    bool link_success = tld_elf64_write_executable(bin_output_path, machine_code_buffer, machine_code_size, get_linker_elf_machine(target.arch));
    if (link_success) {
        printf("[Step 3/3 - Linker]: Final production executable linked: %s\n", bin_output_path);
    }

    teko_project_free(config);
    printf("\n[Compilation Pipeline Executed Successfully].\n");
    return 0;
}
